language: python
python:
  - 3.5
branches:
  only:
    - master
    - develop
    - /^release-v(\d+.){0,2}\d+$/
before_install:
    - pip install flake8
    - pip install pytest pytest-asyncio
install:
  - pip install -r requirements.txt
env:
  - PYTHONPATH=.
script:
  - nosetests
  - flake8 run.py config.template.py cactusbot/
  - python -m pytest tests/
