site_name: CactusBot Documentation
repo_url: https://github.com/CactusDev/CactusBot
site_author: CactusDev
pages:
  - Home: index.md
  - Usage:
    - "!command": usage/command.md
  - Developer: developer/*
